steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helloworld:$latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/helloworld:$latest"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "klt-test-wwbe"
      - "--container-image"
      - "gcr.io/$PROJECT_ID/helloworld:$latest"
      - "--region"
      - "us-central1"

images:
  - "gcr.io/$PROJECT_ID/helloworld:$latest"
