steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helloworld:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/helloworld:latest"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "nginx-vm"
      - "--container-image"
      - "gcr.io/$PROJECT_ID/helloworld:latest"
      - "--zone"
      - "asia-east1-a"


images:
  - "gcr.io/$PROJECT_ID/helloworld:latest"
